spring.application.name=inventariosTintoSentido
# Conexion a mysql
spring.datasource.url=jdbc:mysql://localhost:3306/inventariosTintoSentido_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurar el patron del log (en lugar de logback-spring.xml)
logging.pattern.console=[%thread] %-5level: %logger - %msg%n

# Configurar el nivel del log (INFO en este caso)
logging.level.root=INFO
spring.main.banner-mode=off